version: "2"

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [gosec]
        path: _test\.go$

output:
  sort-order:
    - file
